### ISSUE TITLE
Convertion to TFS revscriptsys

### ISSUE THREAD

**Issue by Nottinghster** [soul4soul/ot-monster-converter#32] opened 2021-08-03 12:41 UTC
If you try to convert a XML monster that have loot inside a bag, those are not converted to the new format.

Example of how it should be:
```lua
monster.loot = {
	{id = "gold coin", chance = 60000, maxCount = 100},
	{id = 1987, chance = 60000, -- bag
		child = {
			{id = "platinum coin", chance = 60000, maxCount = 100},
			{id = "crystal coin", chance = 60000, maxCount = 100}
		}
	}
}
```

Example of how it is right now:
```lua
monster.loot = {
	{id = 7393, chance = 600},
	{id = 7382, chance = 575},
	{id = 2472, chance = 575},
	{id = 2418, chance = 1900},
	{id = 2514, chance = 975},
	{id = 2520, chance = 1225},
	{id = 2470, chance = 900},
	{id = 2393, chance = 2125},
	{id = 2179, chance = 1575},
	{id = 5954, chance = 1050},
	{id = 2151, chance = 3625},
	{id = 2396, chance = 1050},
	{id = 2795, chance = 11425, maxCount = 6},
	{id = 2462, chance = 1600},
	{id = 2176, chance = 3225},
	{id = 2165, chance = 1850},
	{id = 1987, chance = 100000} --bag
}
```
Example of XML file:
```xml
<loot>
    <item id="7393" chance="600" /><!-- demon trophy -->
    <item id="7382" chance="575" /><!-- demonrage sword -->
    <item id="2472" chance="575" /><!-- magic plate armor -->
    <item id="2418" chance="1900" /><!-- golden sickle -->
    <item id="2514" chance="975" /><!-- mastermind shield -->
    <item id="2520" chance="1225" /><!-- demon shield -->
    <item id="2470" chance="900" /><!-- golden legs -->
    <item id="2393" chance="2125" /><!-- giant sword -->
    <item id="2179" chance="1575" /><!-- gold ring -->
    <item id="5954" chance="1050" /><!-- demon horn -->
    <item id="2151" chance="3625" /><!-- talon -->
    <item id="2396" chance="1050" /><!-- ice rapier -->
    <item id="2795" countmax="6" chance="11425" /><!-- fire mushroom -->
    <item id="2462" chance="1600" /><!-- devil helmet -->
    <item id="2176" chance="3225" /><!-- orb -->
    <item id="2165" chance="1850" /><!-- stealth ring -->
    <item id="1987" chance="100000"><!-- bag -->
        <item id="2164" chance="725" /><!-- might ring -->
        <item id="2171" chance="1150" /><!-- platinum amulet -->
        <item id="2432" chance="4325" /><!-- fire axe -->
        <item id="1982" chance="1725" /><!-- purple tome -->
        <item id="7368" countmax="5" chance="3375" /><!-- assassin star -->
        <item id="2387" chance="18750" /><!-- double axe -->
        <item id="7591" chance="700" /> <!-- great health potion -->
        <item id="2214" chance="925" /><!-- ring of healing -->
        <item id="2149" chance="9925" /><!-- small emerald -->
        <item id="8473" countmax="3" chance="11550" /> <!-- ultimate health potion -->
        <item id="2152" chance="66300" /><!-- platinum coin -->
        <item id="7590" countmax="3" chance="8825" /> <!-- great mana potion -->
        <item id="2148" countmax="100" chance="40800" /><!-- gold coin -->
        <item id="2148" countmax="100" chance="40800" /><!-- gold coin -->
    </item>
</loot>
```

**Comment by soul4soul** [comment] 2021-08-04 21:31
🎉 Hey a user appeared! Thanks for the report, this is actually a duplicate of #13 so I'm going to close it. I haven't implemented support for parsing nested items yet. I was secretly planning to never add the feature hoping no one used nested loop anymore. Next time I work on the converter I will look into adding support for nested loot.

**Closed by soul4soul** 2021-08-04 21:31 UTC
